import type { NormalizedSignal } from "./normalizeCiosSignals";

const MIOS_SIGNALS: NormalizedSignal[] = [
  { id: "mios_01", text: "Mortality and hospitalization reduction established strong outcome credibility", caveat: "Demonstrated survival benefit shifted heart failure treatment from symptomatic control to outcome modification", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Demonstrated survival benefit shifted heart failure treatment from symptomatic control to outcome modification" } },
  { id: "mios_02", text: "LDL reduction was dramatic but early outcome evidence lag created adoption hesitation", caveat: "Strong biomarker effect alone was insufficient until cardiovascular outcomes data matured", direction: "negative", strength: "Medium", reliability: "Confirmed", impact: "Medium", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Strong biomarker effect alone was insufficient until cardiovascular outcomes data matured" } },
  { id: "mios_03", text: "Consistent efficacy across multiple inflammatory endpoints strengthened platform credibility", caveat: "Multi-indication success created perception of a dependable mechanism rather than a niche therapy", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Multi-indication success created perception of a dependable mechanism rather than a niche therapy" } },
  { id: "mios_04", text: "Durable survival benefit established trust in immunotherapy mechanism", caveat: "Durable response shifted oncology practice patterns toward checkpoint inhibitors", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Durable response shifted oncology practice patterns toward checkpoint inhibitors" } },
  { id: "mios_05", text: "Slowing disease progression without symptom reversal required reframing clinical expectations", caveat: "Benefit was meaningful but not immediately perceptible to patients", direction: "negative", strength: "Medium", reliability: "Confirmed", impact: "Medium", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Benefit was meaningful but not immediately perceptible to patients" } },
  { id: "mios_06", text: "Transformational efficacy in rare disease justified rapid adoption despite high cost", caveat: "Magnitude of benefit outweighed economic barriers", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Magnitude of benefit outweighed economic barriers" } },
  { id: "mios_07", text: "Broad genotype coverage dramatically expanded eligible patient population", caveat: "Expanded eligibility accelerated market penetration", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Expanded eligibility accelerated market penetration" } },
  { id: "mios_08", text: "Weight loss magnitude exceeded historical expectations for pharmacologic therapy", caveat: "Effect size reset clinician expectations for obesity treatment", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Effect size reset clinician expectations for obesity treatment" } },
  { id: "mios_09", text: "Cardiovascular mortality reduction expanded positioning beyond glycemic control", caveat: "Outcome benefit redefined therapeutic value proposition", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Outcome benefit redefined therapeutic value proposition" } },
  { id: "mios_10", text: "Safety signal emergence constrained long-term adoption trajectory", caveat: "Risk perception can override efficacy in chronic disease settings", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Risk perception can override efficacy in chronic disease settings" } },
];

const BAOS_SIGNALS: NormalizedSignal[] = [
  { id: "baos_01", text: "Physician inertia slowed switching from ACE inhibitors despite superior outcomes", caveat: "Clinical superiority does not automatically overcome established prescribing routines", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Clinical superiority does not automatically overcome established prescribing routines" } },
  { id: "baos_02", text: "Prior authorization complexity reduced prescribing enthusiasm", caveat: "Administrative burden can suppress uptake regardless of clinical value", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Administrative burden can suppress uptake regardless of clinical value" } },
  { id: "baos_03", text: "Visible patient improvement reinforced clinician confidence and accelerated adoption", caveat: "Observable benefit strengthens prescribing momentum", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Observable benefit strengthens prescribing momentum" } },
  { id: "baos_04", text: "Strong KOL advocacy normalized checkpoint inhibitor use", caveat: "Expert endorsement accelerates guideline acceptance", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Expert endorsement accelerates guideline acceptance" } },
  { id: "baos_05", text: "Patient perception of limited symptom improvement reduced adherence motivation", caveat: "Lack of felt benefit can weaken persistence", direction: "negative", strength: "Medium", reliability: "Confirmed", impact: "Medium", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Lack of felt benefit can weaken persistence" } },
  { id: "baos_06", text: "Parent advocacy created strong demand pressure for early treatment", caveat: "Advocacy groups can accelerate therapy uptake", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Advocacy groups can accelerate therapy uptake" } },
  { id: "baos_07", text: "Rapid visible improvement created strong word-of-mouth momentum among patients", caveat: "Peer experience strongly influences treatment demand", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Peer experience strongly influences treatment demand" } },
  { id: "baos_08", text: "High patient demand exceeded supply capacity, constraining adoption speed", caveat: "Supply limitations can cap early uptake", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Supply limitations can cap early uptake" } },
  { id: "baos_09", text: "Cardiologist adoption expanded use beyond endocrinology", caveat: "New prescriber segments increase growth velocity", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "New prescriber segments increase growth velocity" } },
  { id: "baos_10", text: "Safety warnings increased clinician caution in long-term prescribing", caveat: "Risk perception can quickly change prescribing behavior", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "MIOS_BAOS_Calibration", programId: "MIOS-BAOS-CAL-01", whyItMatters: "Risk perception can quickly change prescribing behavior" } },
];

const ARIKAYCE_ANALOG_SIGNALS: NormalizedSignal[] = [
  { id: "analog_01", text: "Slowing disease progression without immediate symptom relief required expectation reframing", caveat: "Physicians initially hesitated because patients did not feel dramatically better, even though disease progression slowed", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Physicians initially hesitated because patients did not feel dramatically better, even though disease progression slowed" } },
  { id: "analog_02", text: "Durable physiologic improvement drove rapid adoption despite variability in symptom response", caveat: "Durable improvement in lung function created strong confidence even when individual symptoms varied", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Durable improvement in lung function created strong confidence even when individual symptoms varied" } },
  { id: "analog_03", text: "Modest symptom benefit but clear disease-modifying effect required education to drive uptake", caveat: "Physicians needed reassurance that slowing decline was clinically meaningful even without dramatic symptom relief", direction: "negative", strength: "Medium", reliability: "Confirmed", impact: "Medium", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Physicians needed reassurance that slowing decline was clinically meaningful even without dramatic symptom relief" } },
  { id: "analog_04", text: "Strong biomarker improvement preceded widespread confidence in clinical outcomes", caveat: "Clinicians waited for outcome confirmation before changing prescribing behavior", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Clinicians waited for outcome confirmation before changing prescribing behavior" } },
  { id: "analog_05", text: "Consistent improvement across multiple endpoints built rapid confidence in treatment value", caveat: "Alignment between symptom improvement and objective measures reinforced trust", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Alignment between symptom improvement and objective measures reinforced trust" } },
  { id: "analog_06", text: "Mortality benefit did not immediately overcome physician inertia", caveat: "Even strong outcome data required time for clinicians to change established practice patterns", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Even strong outcome data required time for clinicians to change established practice patterns" } },
  { id: "analog_07", text: "Transformational efficacy outweighed concerns about administration burden", caveat: "Clear clinical benefit justified logistical complexity", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Clear clinical benefit justified logistical complexity" } },
  { id: "analog_08", text: "Safety signal emergence reduced clinician confidence despite strong efficacy", caveat: "Risk perception can outweigh positive efficacy signals", direction: "negative", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Risk perception can outweigh positive efficacy signals" } },
  { id: "analog_09", text: "Targeted efficacy in a defined population accelerated physician confidence", caveat: "Clear patient selection criteria reduced uncertainty in prescribing decisions", direction: "positive", strength: "High", reliability: "Confirmed", impact: "High", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Clear patient selection criteria reduced uncertainty in prescribing decisions" } },
  { id: "analog_10", text: "High perceived clinical value overcame initial payer hesitation", caveat: "Strong perceived benefit can drive system-level alignment", direction: "positive", strength: "Medium", reliability: "Probable", impact: "Medium", category: "evidence", source: "system", accepted: true, signal_class: "observed", signal_family: "brand_clinical_regulatory", source_type: "MIOS/BAOS Import", priority_source: "observed_verified", is_locked: true, workbook_meta: { sourceWorkbook: "ARIKAYCE_Analog", programId: "ARIKAYCE-ANALOG-01", whyItMatters: "Strong perceived benefit can drive system-level alignment" } },
];

export function getPrebuiltMiosSignals(): NormalizedSignal[] {
  return MIOS_SIGNALS.map(s => ({ ...s }));
}

export function getPrebuiltBaosSignals(): NormalizedSignal[] {
  return BAOS_SIGNALS.map(s => ({ ...s }));
}

export function getPrebuiltAnalogSignals(): NormalizedSignal[] {
  return ARIKAYCE_ANALOG_SIGNALS.map(s => ({ ...s }));
}

export function getAllPrebuiltSignals(): NormalizedSignal[] {
  return [
    ...getPrebuiltMiosSignals(),
    ...getPrebuiltBaosSignals(),
    ...getPrebuiltAnalogSignals(),
  ];
}
