import { db } from "@workspace/db";
import {
  casesTable,
  signalsTable,
  actorsTable,
  specialtyActorSetsTable,
  caseLibraryTable,
  calibrationLogTable,
  scenariosTable,
  guidanceTable,
  fieldIntelligenceTable,
  watchlistTable,
} from "@workspace/db";
import { randomUUID } from "crypto";

export async function seedDatabase(): Promise<{ success: boolean; message: string }> {
  try {
    const existingCases = await db.select().from(casesTable).limit(1);
    if (existingCases.length > 0) {
      return { success: true, message: "Database already seeded." };
    }

    const caseId = randomUUID();
    await db.insert(casesTable).values({
      id: caseId,
      caseId: "CASE-001",
      strategicQuestion:
        "Will the monitored brand move closer to target adoption given the current validated signal set?",
      outcomeDefinition:
        "Net probability that the target outcome becomes more likely after signal validation and actor-response translation.",
      timeHorizon: "12 months",
      priorProbability: 0.45,
      currentProbability: 0.5995,
      confidenceLevel: "High",
      primaryBrand: "ARIKAYCE",
      primarySpecialtyProfile: "General",
      payerEnvironment: "Balanced",
      guidelineLeverage: "Medium",
      competitorProfile: "Entrenched standard of care",
      topSupportiveActor: "Academic KOLs",
      topConstrainingActor: "Competitor Counteraction",
    });

    await db.insert(signalsTable).values([
      {
        id: randomUUID(),
        signalId: "CS-001",
        caseId: "CASE-001",
        candidateId: "CS-001",
        brand: "ARIKAYCE",
        signalDescription:
          "A new publication appears to strengthen the bridge between microbiology and function.",
        signalType: "Clinical evidence",
        direction: "Positive",
        strengthScore: 4,
        reliabilityScore: 5,
        likelihoodRatio: 1.32,
        route: "CIOS→MIOS",
        targetPopulation: "Pulmonology / NTM-focused",
        miosFlag: "Yes",
        ohosFlag: "No",
        weightedSignalScore: 20,
        actorAdjustedImpact: 0.748,
        activeLikelihoodRatio: 1.32,
        absoluteImpact: 0.748,
      },
      {
        id: randomUUID(),
        signalId: "CS-002",
        caseId: "CASE-001",
        candidateId: "CS-002",
        brand: "ARIKAYCE",
        signalDescription:
          "Multiple accounts continue to ask for a simpler identification and referral story.",
        signalType: "Field intelligence",
        direction: "Negative",
        strengthScore: 4,
        reliabilityScore: 4,
        likelihoodRatio: 0.68,
        route: "CIOS→MIOS+OHOS",
        targetPopulation: "Pulmonology / community",
        miosFlag: "Yes",
        ohosFlag: "Yes",
        weightedSignalScore: 16,
        actorAdjustedImpact: -0.675,
        activeLikelihoodRatio: 0.68,
        absoluteImpact: 0.675,
      },
      {
        id: randomUUID(),
        signalId: "CS-003",
        caseId: "CASE-001",
        candidateId: "CS-003",
        brand: "ARIKAYCE",
        signalDescription:
          "Emerging coverage shift could reduce reimbursement obstacles in target accounts.",
        signalType: "Access / commercial",
        direction: "Positive",
        strengthScore: 5,
        reliabilityScore: 4,
        likelihoodRatio: 1.4,
        route: "CIOS→OHOS",
        targetPopulation: "Pulmonology / general",
        miosFlag: "No",
        ohosFlag: "Yes",
        weightedSignalScore: 20,
        actorAdjustedImpact: 0.678,
        activeLikelihoodRatio: 1.4,
        absoluteImpact: 0.678,
      },
    ]);

    await db.insert(actorsTable).values([
      {
        id: randomUUID(),
        actorName: "Academic KOLs",
        influenceWeight: 0.2037,
        positiveResponseFactor: 1.15,
        negativeResponseFactor: 0.88,
        outcomeOrientation: 1,
        roleInSystem: "Cross-specialty scientific validators and early adopters.",
        baseInfluenceWeight: 0.2,
        canonicalActor: "Academic KOLs",
        specialtyProfile: "General",
        slotIndex: 0,
        rawWeight: 0.21,
        basePositiveResponseFactor: 1.15,
        baseNegativeResponseFactor: 0.88,
      },
      {
        id: randomUUID(),
        actorName: "Community Physicians",
        influenceWeight: 0.2211,
        positiveResponseFactor: 0.9025,
        negativeResponseFactor: 1.188,
        outcomeOrientation: 1,
        roleInSystem: "Broad treating base whose behavior determines real-world conversion.",
        baseInfluenceWeight: 0.24,
        canonicalActor: "Community Physicians",
        specialtyProfile: "General",
        slotIndex: 1,
        rawWeight: 0.228,
        basePositiveResponseFactor: 0.95,
        baseNegativeResponseFactor: 1.1,
      },
      {
        id: randomUUID(),
        actorName: "Specialty Extenders / PCPs",
        influenceWeight: 0.1164,
        positiveResponseFactor: 0.85,
        negativeResponseFactor: 1.05,
        outcomeOrientation: 1,
        roleInSystem: "Secondary prescribers or extenders who amplify practical uptake.",
        baseInfluenceWeight: 0.12,
        canonicalActor: "Health Systems",
        specialtyProfile: "General",
        slotIndex: 2,
        rawWeight: 0.12,
        basePositiveResponseFactor: 0.85,
        baseNegativeResponseFactor: 1.05,
      },
      {
        id: randomUUID(),
        actorName: "Payers / Access",
        influenceWeight: 0.1833,
        positiveResponseFactor: 0.8,
        negativeResponseFactor: 1.2,
        outcomeOrientation: 1,
        roleInSystem: "Coverage and reimbursement gatekeepers.",
        baseInfluenceWeight: 0.18,
        canonicalActor: "Payers / Access",
        specialtyProfile: "General",
        slotIndex: 3,
        rawWeight: 0.189,
        basePositiveResponseFactor: 0.8,
        baseNegativeResponseFactor: 1.2,
      },
      {
        id: randomUUID(),
        actorName: "Guideline / Society Bodies",
        influenceWeight: 0.1358,
        positiveResponseFactor: 1.25,
        negativeResponseFactor: 0.9,
        outcomeOrientation: 1,
        roleInSystem: "Formal recommendation-setting organizations.",
        baseInfluenceWeight: 0.14,
        canonicalActor: "Guideline Bodies",
        specialtyProfile: "General",
        slotIndex: 4,
        rawWeight: 0.14,
        basePositiveResponseFactor: 1.25,
        baseNegativeResponseFactor: 0.9,
      },
      {
        id: randomUUID(),
        actorName: "Competitor Counteraction",
        influenceWeight: 0.1397,
        positiveResponseFactor: 0.9,
        negativeResponseFactor: 1.12,
        outcomeOrientation: -1,
        roleInSystem: "Counter-detailing, access defense, and class-noise response.",
        baseInfluenceWeight: 0.12,
        canonicalActor: "Competitor Counteraction",
        specialtyProfile: "General",
        slotIndex: 5,
        rawWeight: 0.144,
        basePositiveResponseFactor: 0.9,
        baseNegativeResponseFactor: 1.12,
      },
    ]);

    const specialtyProfiles = [
      {
        profile: "General",
        actors: [
          { slot: 1, display: "Academic KOLs", canonical: "Academic KOLs", role: "Cross-specialty scientific validators and early adopters.", weight: 0.2, pos: 1.15, neg: 0.88, orient: 1 },
          { slot: 2, display: "Community Physicians", canonical: "Community Physicians", role: "Broad treating base whose behavior determines real-world conversion.", weight: 0.24, pos: 0.95, neg: 1.1, orient: 1 },
          { slot: 3, display: "Specialty Extenders / PCPs", canonical: "Health Systems", role: "Secondary prescribers or extenders who amplify practical uptake.", weight: 0.12, pos: 0.85, neg: 1.05, orient: 1 },
          { slot: 4, display: "Payers / Access", canonical: "Payers / Access", role: "Coverage and reimbursement gatekeepers.", weight: 0.18, pos: 0.8, neg: 1.2, orient: 1 },
          { slot: 5, display: "Guideline / Society Bodies", canonical: "Guideline Bodies", role: "Formal recommendation-setting organizations.", weight: 0.14, pos: 1.25, neg: 0.9, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Counter-detailing, access defense, and class-noise response.", weight: 0.12, pos: 0.9, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Pulmonology / rare disease",
        actors: [
          { slot: 1, display: "Academic Pulmonologists", canonical: "Academic KOLs", role: "Reference-center pulmonologists and rare-disease KOLs shaping standards.", weight: 0.24, pos: 1.2, neg: 0.85, orient: 1 },
          { slot: 2, display: "Community Pulmonologists", canonical: "Community Physicians", role: "Office and hospital pulmonologists who determine scale.", weight: 0.24, pos: 0.95, neg: 1.08, orient: 1 },
          { slot: 3, display: "ID / Bronchiectasis Specialists", canonical: "Guideline Bodies", role: "Subspecialty experts influencing treatment algorithms and referral logic.", weight: 0.12, pos: 1.1, neg: 0.92, orient: 1 },
          { slot: 4, display: "Payers / Rare Disease", canonical: "Payers / Access", role: "Specialty pharmacy and rare-disease access gatekeepers.", weight: 0.18, pos: 0.78, neg: 1.22, orient: 1 },
          { slot: 5, display: "Guideline / ATS / ERS", canonical: "Health Systems", role: "Society bodies shaping clinical practice statements.", weight: 0.12, pos: 1.15, neg: 0.9, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Competing inhaled therapies and alternative treatment pathways.", weight: 0.1, pos: 0.9, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Cardiology / mixed specialist",
        actors: [
          { slot: 1, display: "Academic Cardiologists", canonical: "Academic KOLs", role: "Trial investigators and congress-visible cardiology KOLs.", weight: 0.2, pos: 1.12, neg: 0.9, orient: 1 },
          { slot: 2, display: "Community Cardiologists", canonical: "Community Physicians", role: "High-volume community cardiologists driving real-world adoption.", weight: 0.26, pos: 1.0, neg: 1.08, orient: 1 },
          { slot: 3, display: "Interventional / EP Specialists", canonical: "Academic KOLs", role: "Procedure-performing subspecialists driving device or therapy adoption.", weight: 0.12, pos: 1.08, neg: 0.94, orient: 1 },
          { slot: 4, display: "Payers / Access", canonical: "Payers / Access", role: "Medicare and commercial access decision-makers.", weight: 0.18, pos: 0.82, neg: 1.18, orient: 1 },
          { slot: 5, display: "Hospital Systems / Cath Labs", canonical: "Health Systems", role: "Operational implementers, service-line leaders, and site economics owners.", weight: 0.12, pos: 0.88, neg: 1.05, orient: 1 },
          { slot: 6, display: "Competitor Device / Pharma Response", canonical: "Competitor Counteraction", role: "Incumbent therapeutic response and contracting defense.", weight: 0.12, pos: 0.92, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Oncology / academic-led",
        actors: [
          { slot: 1, display: "Academic Oncologists", canonical: "Academic KOLs", role: "Academic investigators and congress-visible opinion leaders.", weight: 0.24, pos: 1.18, neg: 0.86, orient: 1 },
          { slot: 2, display: "Community Oncologists", canonical: "Community Physicians", role: "Community treatment networks that determine broad penetration.", weight: 0.22, pos: 0.96, neg: 1.08, orient: 1 },
          { slot: 3, display: "Tumor Boards / Pathway Committees", canonical: "Guideline Bodies", role: "Pathway and protocol setters shaping regimen choice.", weight: 0.15, pos: 1.12, neg: 0.92, orient: 1 },
          { slot: 4, display: "Payers / Pathways", canonical: "Payers / Access", role: "Access and pathway gatekeepers for line-of-therapy use.", weight: 0.15, pos: 0.82, neg: 1.16, orient: 1 },
          { slot: 5, display: "Infusion Networks / Health Systems", canonical: "Health Systems", role: "Operational infusion and site-of-care stakeholders.", weight: 0.12, pos: 0.88, neg: 1.06, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Class competition, sequencing defense, and trial countermessaging.", weight: 0.12, pos: 0.92, neg: 1.12, orient: -1 },
        ],
      },
    ];

    for (const sp of specialtyProfiles) {
      for (const actor of sp.actors) {
        await db.insert(specialtyActorSetsTable).values({
          id: randomUUID(),
          primarySpecialtyProfile: sp.profile,
          actorSlot: actor.slot,
          displayActor: actor.display,
          canonicalActor: actor.canonical,
          roleInSystem: actor.role,
          baseInfluenceWeight: actor.weight,
          basePositiveResponseFactor: actor.pos,
          baseNegativeResponseFactor: actor.neg,
          outcomeOrientation: actor.orient,
        });
      }
    }

    await db.insert(caseLibraryTable).values([
      {
        id: randomUUID(),
        caseId: "ANALOG-001",
        therapyArea: "Pulmonology / rare disease",
        productType: "Medication",
        specialty: "Pulmonology",
        evidenceType: "Phase 3 RCT",
        lifecycleStage: "Launch / early adoption",
        actorMix: "KOL-led with community resistance",
        marketAccessConditions: "Specialty pharmacy, prior auth required",
        outcomePattern: "Delayed adoption — 18-24 months to meaningful uptake",
        adoptionTrajectory: "Slow ramp, then inflection after guideline inclusion",
        keyInflectionSignals: "ATS guideline mention, payer policy expansion",
        finalObservedOutcome: "Moderate adoption in academic centers; limited community penetration",
        finalProbability: 0.55,
        notes: "NTM-bronchiectasis orphan-adjacent drug. Strong KOL support did not translate to community at launch.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-002",
        therapyArea: "Cardiology",
        productType: "Device",
        specialty: "Cardiology / Interventional",
        evidenceType: "Real-world evidence + RCT",
        lifecycleStage: "Growth phase",
        actorMix: "Interventionalist-led, hospital system adoption",
        marketAccessConditions: "DRG + add-on payment, coverage expanding",
        outcomePattern: "Rapid uptake among early adopters, broader market needed",
        adoptionTrajectory: "Fast in high-volume centers, slower in community",
        keyInflectionSignals: "ACC guideline class IIa, CMS coverage decision",
        finalObservedOutcome: "Strong adoption at academic centers; community lag remains",
        finalProbability: 0.72,
        notes: "Device adoption in structural heart — operator dependence created uneven rollout.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-003",
        therapyArea: "Infectious Disease",
        productType: "Medication",
        specialty: "Infectious Disease / Pulmonology",
        evidenceType: "Retrospective registry + open-label extension",
        lifecycleStage: "Established use",
        actorMix: "ID specialists and pulmonologists co-managing",
        marketAccessConditions: "Favorable access after initial coverage challenge",
        outcomePattern: "Gradual guideline-anchored adoption",
        adoptionTrajectory: "Consistent upward trend after IDSA guideline update",
        keyInflectionSignals: "IDSA/ATS joint guideline, payer coverage liberalization",
        finalObservedOutcome: "Near-guideline-level adoption in academic ID centers",
        finalProbability: 0.68,
        notes: "Strong parallel to NTM-MAC therapy adoption patterns.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-004",
        therapyArea: "Pulmonology",
        productType: "Medication",
        specialty: "Pulmonology / community",
        evidenceType: "Phase 3 RCT (exacerbation endpoint)",
        lifecycleStage: "Mature — label expansion phase",
        actorMix: "Community pulmonologists, payer-sensitive",
        marketAccessConditions: "Commercially competitive, step therapy required",
        outcomePattern: "Plateau after initial launch, rebooted by label expansion",
        adoptionTrajectory: "Flat then upward after indication expansion",
        keyInflectionSignals: "Exacerbation data publication, label expansion approval",
        finalObservedOutcome: "Broad community adoption after exacerbation data widely adopted",
        finalProbability: 0.63,
        notes: "COPD/bronchiectasis community response — step therapy hurdles delayed adoption.",
      },
    ]);

    await db.insert(calibrationLogTable).values({
      id: randomUUID(),
      forecastId: "FCAST-001",
      caseId: "CASE-001",
      predictedProbability: 0.5995,
      notes: "Initial V18 forecast from actor-reaction engine",
      snapshotJson: JSON.stringify({ version: "V18", priorProbability: 0.45 }),
    });

    await db.insert(scenariosTable).values([
      {
        id: randomUUID(),
        scenarioId: "SCN-001",
        caseId: "CASE-001",
        hypotheticalSignal: "Single positive high-strength signal",
        direction: "Positive",
        estimatedImpact: 0.15,
        newProbability: 0.7495,
        notes: "Illustrative upside sensitivity",
      },
      {
        id: randomUUID(),
        scenarioId: "SCN-002",
        caseId: "CASE-001",
        hypotheticalSignal: "Single negative high-strength signal",
        direction: "Negative",
        estimatedImpact: -0.15,
        newProbability: 0.4495,
        notes: "Illustrative downside sensitivity",
      },
    ]);

    await db.insert(guidanceTable).values([
      {
        id: randomUUID(),
        guidanceId: "GUID-001",
        caseId: "CASE-001",
        keyRiskDriver: "Academic KOLs",
        recommendedAction: "Target supportive actors and close remaining objections",
        targetAudience: "Leadership / field",
        priorityLevel: "High",
        linkedSignalId: "CS-001",
      },
      {
        id: randomUUID(),
        guidanceId: "GUID-002",
        caseId: "CASE-001",
        keyRiskDriver: "Competitor Counteraction",
        recommendedAction: "Route constraining objections to OHOS",
        targetAudience: "Field strategy",
        priorityLevel: "High",
        linkedSignalId: "CS-002",
      },
      {
        id: randomUUID(),
        guidanceId: "GUID-003",
        caseId: "CASE-001",
        keyRiskDriver: "Validated signals",
        recommendedAction: "No MIOS routing needed",
        targetAudience: "Medical strategy",
        priorityLevel: "Medium",
        linkedSignalId: "CS-003",
      },
    ]);

    await db.insert(fieldIntelligenceTable).values({
      id: randomUUID(),
      feedbackId: "FB-001",
      brand: "ARIKAYCE",
      audienceType: "HCP",
      specialty: "Pulmonology",
      subspecialty: "NTM-focused",
      region: "US South",
      sourceRole: "MSL",
      sourceName: "Example KOL",
      signalCategory: "Clinical perception",
      observedBarrier: "Culture conversion seen as less persuasive than symptom improvement",
      rawFieldFeedback:
        "Pulmonologists are asking for a more direct connection between microbiology and fatigue / functioning.",
      beliefShiftRisk: 4,
      messageMismatchRisk: 5,
      accessRisk: 1,
      competitiveRisk: 1,
      urgencyScore: 5,
      credibilityScore: 4,
      frequencyScore: 3,
      potentialImpact: 5,
      totalSignalScore: 17,
      ciosSignalDirection: "Negative",
      suggestedRoute: "CIOS→MIOS+OHOS",
      fieldActionNeeded: "Yes",
      notes: "Use symptom-bridge framing",
    });

    await db.insert(watchlistTable).values([
      {
        id: randomUUID(),
        signalId: "SIG-021",
        signalName: "ATS guideline update discussion",
        signalType: "Regulatory",
        expectedWindow: "ATS meeting",
        owner: "Medical Affairs",
        expectedDirection: "+",
        estimatedImpact: "High",
        evidenceSource: "ATS conference",
        status: "Pending",
        notes: "Guideline panel discussion expected",
      },
      {
        id: randomUUID(),
        signalId: "SIG-022",
        signalName: "Payer coverage expansion",
        signalType: "Commercial",
        expectedWindow: "Next 6 months",
        owner: "Market Access",
        expectedDirection: "+",
        estimatedImpact: "Medium",
        evidenceSource: "Payer policy updates",
        status: "Pending",
        notes: "Monitoring policy bulletins",
      },
      {
        id: randomUUID(),
        signalId: "SIG-023",
        signalName: "Confirmatory trial interim data",
        signalType: "Clinical",
        expectedWindow: "Q4",
        owner: "Clinical Team",
        expectedDirection: "+",
        estimatedImpact: "High",
        evidenceSource: "ClinicalTrials.gov",
        status: "Pending",
        notes: "Interim analysis expected",
      },
    ]);

    return { success: true, message: "Database seeded with workbook sample data." };
  } catch (error) {
    return { success: false, message: `Seed failed: ${error}` };
  }
}
