import { db } from "@workspace/db";
import {
  casesTable,
  signalsTable,
  actorsTable,
  specialtyActorSetsTable,
  caseLibraryTable,
  calibrationLogTable,
  scenariosTable,
  guidanceTable,
  fieldIntelligenceTable,
  watchlistTable,
} from "@workspace/db";
import { randomUUID } from "crypto";

async function clearAll() {
  await db.delete(watchlistTable);
  await db.delete(fieldIntelligenceTable);
  await db.delete(guidanceTable);
  await db.delete(scenariosTable);
  await db.delete(calibrationLogTable);
  await db.delete(caseLibraryTable);
  await db.delete(signalsTable);
  await db.delete(casesTable);
  await db.delete(actorsTable);
  await db.delete(specialtyActorSetsTable);
}

export async function seedDatabase(force = false): Promise<{ success: boolean; message: string }> {
  try {
    if (!force) {
      const existingCases = await db.select().from(casesTable).limit(1);
      if (existingCases.length > 0) {
        return { success: true, message: "Database already seeded." };
      }
    } else {
      await clearAll();
    }

    // ── Demo cases ── 3 archetypes spanning different therapeutic areas.
    // These are illustrative only. CIOS operates for any asset, specialty, and geography.
    await db.insert(casesTable).values([
      {
        id: randomUUID(),
        caseId: "CASE-DEMO-01",
        // Asset metadata
        assetName: "ARIKAYCE",
        assetType: "Medication",
        therapeuticArea: "Rare disease / Orphan",
        diseaseState: "NTM Lung Disease (MAC)",
        specialty: "Pulmonology / Infectious Disease",
        geography: "US",
        // Strategic framing
        strategicQuestion:
          "Will ARIKAYCE achieve target specialist adoption (≥4 Rx/quarter) within 12 months given current validated signals?",
        outcomeDefinition:
          "Target Pulmonologist reaches ≥4 Rx/quarter for NTM MAC patients within forecast horizon.",
        timeHorizon: "12 months",
        priorProbability: 0.45,
        currentProbability: null,
        confidenceLevel: null,
        primaryBrand: "ARIKAYCE",
        primarySpecialtyProfile: "Pulmonology / rare disease",
        payerEnvironment: "Balanced",
        guidelineLeverage: "High",
        competitorProfile: "Entrenched standard of care",
        topSupportiveActor: null,
        topConstrainingActor: null,
        isDemo: "true",
      },
      {
        id: randomUUID(),
        caseId: "CASE-DEMO-02",
        assetName: "CardioAsset X",
        assetType: "Medication",
        therapeuticArea: "Cardiology",
        diseaseState: "Heart Failure with Reduced Ejection Fraction (HFrEF)",
        specialty: "Cardiology",
        geography: "US",
        strategicQuestion:
          "Will CardioAsset X displace entrenched standard-of-care beta-blocker combinations within target cardiologist accounts over 18 months?",
        outcomeDefinition:
          "Target Cardiologist initiates CardioAsset X in ≥3 new HFrEF patients within 18 months.",
        timeHorizon: "18 months",
        priorProbability: 0.35,
        currentProbability: null,
        confidenceLevel: null,
        primaryBrand: "CardioAsset X",
        primarySpecialtyProfile: "Cardiology / mixed specialist",
        payerEnvironment: "Medicare-heavy",
        guidelineLeverage: "High",
        competitorProfile: "Entrenched standard of care",
        topSupportiveActor: null,
        topConstrainingActor: null,
        isDemo: "true",
      },
      {
        id: randomUUID(),
        caseId: "CASE-DEMO-03",
        assetName: "OncoDevice Y",
        assetType: "Device",
        therapeuticArea: "Oncology",
        diseaseState: "NSCLC (Stage III-IV)",
        specialty: "Oncology",
        geography: "US + EU5",
        strategicQuestion:
          "Will tumor-board adoption of OncoDevice Y reach threshold in academic oncology centers within 24 months?",
        outcomeDefinition:
          "Academic tumor board formally incorporates OncoDevice Y into at least one NSCLC treatment pathway.",
        timeHorizon: "24 months",
        priorProbability: 0.55,
        currentProbability: null,
        confidenceLevel: null,
        primaryBrand: "OncoDevice Y",
        primarySpecialtyProfile: "Oncology / academic-led",
        payerEnvironment: "Commercial-heavy",
        guidelineLeverage: "Medium",
        competitorProfile: "Crowded class / multiple competitors",
        topSupportiveActor: null,
        topConstrainingActor: null,
        isDemo: "true",
      },
    ]);

    await db.insert(signalsTable).values([
      {
        id: randomUUID(),
        signalId: "CS-001",
        caseId: "CASE-DEMO-01",
        candidateId: "CS-001",
        brand: "ARIKAYCE",
        signalDescription:
          "A new peer-reviewed publication strengthens the evidence linkage between the primary mechanism and patient outcomes.",
        signalType: "Clinical evidence",
        direction: "Positive",
        strengthScore: 4,
        reliabilityScore: 5,
        likelihoodRatio: 1.32,
        route: "CIOS→MIOS",
        targetPopulation: "Specialist",
        miosFlag: "Yes",
        ohosFlag: "No",
        weightedSignalScore: 20,
        actorAdjustedImpact: null,
        activeLikelihoodRatio: 1.32,
        absoluteImpact: null,
      },
      {
        id: randomUUID(),
        signalId: "CS-002",
        caseId: "CASE-DEMO-01",
        candidateId: "CS-002",
        brand: "ARIKAYCE",
        signalDescription:
          "Field accounts report continued requests for a simpler identification and referral pathway.",
        signalType: "Field intelligence",
        direction: "Negative",
        strengthScore: 4,
        reliabilityScore: 4,
        likelihoodRatio: 0.68,
        route: "CIOS→MIOS+OHOS",
        targetPopulation: "Community specialist",
        miosFlag: "Yes",
        ohosFlag: "Yes",
        weightedSignalScore: 16,
        actorAdjustedImpact: null,
        activeLikelihoodRatio: 0.68,
        absoluteImpact: null,
      },
      {
        id: randomUUID(),
        signalId: "CS-003",
        caseId: "CASE-DEMO-01",
        candidateId: "CS-003",
        brand: "ARIKAYCE",
        signalDescription:
          "Emerging payer coverage shift could reduce reimbursement obstacles in key target accounts.",
        signalType: "Access / commercial",
        direction: "Positive",
        strengthScore: 5,
        reliabilityScore: 4,
        likelihoodRatio: 1.4,
        route: "CIOS→OHOS",
        targetPopulation: "General specialist",
        miosFlag: "No",
        ohosFlag: "Yes",
        weightedSignalScore: 20,
        actorAdjustedImpact: null,
        activeLikelihoodRatio: 1.4,
        absoluteImpact: null,
      },
    ]);

    await db.insert(actorsTable).values([
      {
        id: randomUUID(),
        actorName: "Academic KOLs",
        influenceWeight: 0.2037,
        positiveResponseFactor: 1.15,
        negativeResponseFactor: 0.88,
        outcomeOrientation: 1,
        roleInSystem: "Cross-specialty scientific validators and early adopters.",
        baseInfluenceWeight: 0.2,
        canonicalActor: "Academic KOLs",
        specialtyProfile: "General",
        slotIndex: 0,
        rawWeight: 0.21,
        basePositiveResponseFactor: 1.15,
        baseNegativeResponseFactor: 0.88,
      },
      {
        id: randomUUID(),
        actorName: "Community Physicians",
        influenceWeight: 0.2211,
        positiveResponseFactor: 0.9025,
        negativeResponseFactor: 1.188,
        outcomeOrientation: 1,
        roleInSystem: "Broad treating base whose behavior determines real-world conversion.",
        baseInfluenceWeight: 0.24,
        canonicalActor: "Community Physicians",
        specialtyProfile: "General",
        slotIndex: 1,
        rawWeight: 0.228,
        basePositiveResponseFactor: 0.95,
        baseNegativeResponseFactor: 1.1,
      },
      {
        id: randomUUID(),
        actorName: "Specialty Extenders / PCPs",
        influenceWeight: 0.1164,
        positiveResponseFactor: 0.85,
        negativeResponseFactor: 1.05,
        outcomeOrientation: 1,
        roleInSystem: "Secondary prescribers or extenders who amplify practical uptake.",
        baseInfluenceWeight: 0.12,
        canonicalActor: "Health Systems",
        specialtyProfile: "General",
        slotIndex: 2,
        rawWeight: 0.12,
        basePositiveResponseFactor: 0.85,
        baseNegativeResponseFactor: 1.05,
      },
      {
        id: randomUUID(),
        actorName: "Payers / Access",
        influenceWeight: 0.1833,
        positiveResponseFactor: 0.8,
        negativeResponseFactor: 1.2,
        outcomeOrientation: 1,
        roleInSystem: "Coverage and reimbursement gatekeepers.",
        baseInfluenceWeight: 0.18,
        canonicalActor: "Payers / Access",
        specialtyProfile: "General",
        slotIndex: 3,
        rawWeight: 0.189,
        basePositiveResponseFactor: 0.8,
        baseNegativeResponseFactor: 1.2,
      },
      {
        id: randomUUID(),
        actorName: "Guideline / Society Bodies",
        influenceWeight: 0.1358,
        positiveResponseFactor: 1.25,
        negativeResponseFactor: 0.9,
        outcomeOrientation: 1,
        roleInSystem: "Formal recommendation-setting organizations.",
        baseInfluenceWeight: 0.14,
        canonicalActor: "Guideline Bodies",
        specialtyProfile: "General",
        slotIndex: 4,
        rawWeight: 0.14,
        basePositiveResponseFactor: 1.25,
        baseNegativeResponseFactor: 0.9,
      },
      {
        id: randomUUID(),
        actorName: "Competitor Counteraction",
        influenceWeight: 0.1397,
        positiveResponseFactor: 0.9,
        negativeResponseFactor: 1.12,
        outcomeOrientation: -1,
        roleInSystem: "Counter-detailing, access defense, and class-noise response.",
        baseInfluenceWeight: 0.12,
        canonicalActor: "Competitor Counteraction",
        specialtyProfile: "General",
        slotIndex: 5,
        rawWeight: 0.144,
        basePositiveResponseFactor: 0.9,
        baseNegativeResponseFactor: 1.12,
      },
    ]);

    const specialtyProfiles = [
      {
        profile: "General",
        actors: [
          { slot: 1, display: "Academic KOLs", canonical: "Academic KOLs", role: "Cross-specialty scientific validators and early adopters.", weight: 0.2, pos: 1.15, neg: 0.88, orient: 1 },
          { slot: 2, display: "Community Physicians", canonical: "Community Physicians", role: "Broad treating base whose behavior determines real-world conversion.", weight: 0.24, pos: 0.95, neg: 1.1, orient: 1 },
          { slot: 3, display: "Specialty Extenders / PCPs", canonical: "Health Systems", role: "Secondary prescribers or extenders who amplify practical uptake.", weight: 0.12, pos: 0.85, neg: 1.05, orient: 1 },
          { slot: 4, display: "Payers / Access", canonical: "Payers / Access", role: "Coverage and reimbursement gatekeepers.", weight: 0.18, pos: 0.8, neg: 1.2, orient: 1 },
          { slot: 5, display: "Guideline / Society Bodies", canonical: "Guideline Bodies", role: "Formal recommendation-setting organizations.", weight: 0.14, pos: 1.25, neg: 0.9, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Counter-detailing, access defense, and class-noise response.", weight: 0.12, pos: 0.9, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Pulmonology / rare disease",
        actors: [
          { slot: 1, display: "Academic Specialists", canonical: "Academic KOLs", role: "Reference-center specialists and rare-disease KOLs shaping clinical standards.", weight: 0.24, pos: 1.2, neg: 0.85, orient: 1 },
          { slot: 2, display: "Community Specialists", canonical: "Community Physicians", role: "Community and hospital-based specialists who determine real-world prescribing scale.", weight: 0.24, pos: 0.95, neg: 1.08, orient: 1 },
          { slot: 3, display: "Subspecialty Consultants", canonical: "Guideline Bodies", role: "Subspecialty experts influencing treatment algorithms and referral logic.", weight: 0.12, pos: 1.1, neg: 0.92, orient: 1 },
          { slot: 4, display: "Payers / Rare Disease Access", canonical: "Payers / Access", role: "Specialty pharmacy and rare-disease access gatekeepers.", weight: 0.18, pos: 0.78, neg: 1.22, orient: 1 },
          { slot: 5, display: "Guideline / Society Bodies", canonical: "Health Systems", role: "Society bodies shaping clinical practice statements and recommendation tiers.", weight: 0.12, pos: 1.15, neg: 0.9, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Competing therapies and alternative treatment approaches in the rare disease space.", weight: 0.1, pos: 0.9, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Cardiology / mixed specialist",
        actors: [
          { slot: 1, display: "Academic Cardiologists", canonical: "Academic KOLs", role: "Trial investigators and congress-visible cardiology KOLs.", weight: 0.2, pos: 1.12, neg: 0.9, orient: 1 },
          { slot: 2, display: "Community Cardiologists", canonical: "Community Physicians", role: "High-volume community cardiologists driving real-world adoption.", weight: 0.26, pos: 1.0, neg: 1.08, orient: 1 },
          { slot: 3, display: "Interventional / EP Specialists", canonical: "Academic KOLs", role: "Procedure-performing subspecialists driving device or therapy adoption.", weight: 0.12, pos: 1.08, neg: 0.94, orient: 1 },
          { slot: 4, display: "Payers / Access", canonical: "Payers / Access", role: "Medicare and commercial access decision-makers.", weight: 0.18, pos: 0.82, neg: 1.18, orient: 1 },
          { slot: 5, display: "Hospital Systems / Cath Labs", canonical: "Health Systems", role: "Operational implementers, service-line leaders, and site economics owners.", weight: 0.12, pos: 0.88, neg: 1.05, orient: 1 },
          { slot: 6, display: "Competitor Response", canonical: "Competitor Counteraction", role: "Incumbent therapeutic response and contracting defense.", weight: 0.12, pos: 0.92, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Oncology / academic-led",
        actors: [
          { slot: 1, display: "Academic Oncologists", canonical: "Academic KOLs", role: "Academic investigators and congress-visible opinion leaders.", weight: 0.24, pos: 1.18, neg: 0.86, orient: 1 },
          { slot: 2, display: "Community Oncologists", canonical: "Community Physicians", role: "Community treatment networks that determine broad penetration.", weight: 0.22, pos: 0.96, neg: 1.08, orient: 1 },
          { slot: 3, display: "Tumor Boards / Pathway Committees", canonical: "Guideline Bodies", role: "Pathway and protocol setters shaping regimen choice.", weight: 0.15, pos: 1.12, neg: 0.92, orient: 1 },
          { slot: 4, display: "Payers / Pathways", canonical: "Payers / Access", role: "Access and pathway gatekeepers for line-of-therapy use.", weight: 0.15, pos: 0.82, neg: 1.16, orient: 1 },
          { slot: 5, display: "Infusion Networks / Health Systems", canonical: "Health Systems", role: "Operational infusion and site-of-care stakeholders.", weight: 0.12, pos: 0.88, neg: 1.06, orient: 1 },
          { slot: 6, display: "Competitor Counteraction", canonical: "Competitor Counteraction", role: "Class competition, sequencing defense, and trial countermessaging.", weight: 0.12, pos: 0.92, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Dermatology / community-led",
        actors: [
          { slot: 1, display: "Academic Dermatologists", canonical: "Academic KOLs", role: "Derm KOLs and academic protocol setters.", weight: 0.18, pos: 1.1, neg: 0.9, orient: 1 },
          { slot: 2, display: "Community Dermatologists", canonical: "Community Physicians", role: "High-volume community derm driving the majority of prescriptions.", weight: 0.28, pos: 1.0, neg: 1.1, orient: 1 },
          { slot: 3, display: "Nurse Practitioners / PAs", canonical: "Health Systems", role: "Extenders with growing prescribing authority in derm.", weight: 0.14, pos: 0.9, neg: 1.05, orient: 1 },
          { slot: 4, display: "Payers / Step Therapy", canonical: "Payers / Access", role: "Payers enforcing step therapy and prior authorization.", weight: 0.16, pos: 0.8, neg: 1.2, orient: 1 },
          { slot: 5, display: "Guideline / AAD Bodies", canonical: "Guideline Bodies", role: "AAD and society guideline setters influencing treatment ladders.", weight: 0.12, pos: 1.2, neg: 0.9, orient: 1 },
          { slot: 6, display: "Biosimilar / Generic Pressure", canonical: "Competitor Counteraction", role: "Biosimilar entrants and class crowding.", weight: 0.12, pos: 0.88, neg: 1.15, orient: -1 },
        ],
      },
      {
        profile: "Psychiatry / access-sensitive",
        actors: [
          { slot: 1, display: "Academic Psychiatrists", canonical: "Academic KOLs", role: "Academic psychiatry opinion leaders and training program directors.", weight: 0.16, pos: 1.1, neg: 0.92, orient: 1 },
          { slot: 2, display: "Community Psychiatrists", canonical: "Community Physicians", role: "Office-based and community psychiatrists managing broad patient volumes.", weight: 0.22, pos: 0.95, neg: 1.1, orient: 1 },
          { slot: 3, display: "PCPs / Prescribing NPs", canonical: "Health Systems", role: "Primary care and NPs managing psychiatric conditions with limited specialist access.", weight: 0.2, pos: 0.88, neg: 1.08, orient: 1 },
          { slot: 4, display: "Payers / Access / PA", canonical: "Payers / Access", role: "Prior authorization and formulary gatekeepers in a restrictive landscape.", weight: 0.2, pos: 0.78, neg: 1.22, orient: 1 },
          { slot: 5, display: "Advocacy / Patient Groups", canonical: "Guideline Bodies", role: "Patient advocacy groups and mental health societies influencing adoption sentiment.", weight: 0.12, pos: 1.15, neg: 0.95, orient: 1 },
          { slot: 6, display: "Competitor / Generic Response", canonical: "Competitor Counteraction", role: "Generic entrants, older branded alternatives, and payer-preferred alternatives.", weight: 0.1, pos: 0.88, neg: 1.12, orient: -1 },
        ],
      },
      {
        profile: "Infectious disease / guideline-led",
        actors: [
          { slot: 1, display: "ID Specialists / Consultants", canonical: "Academic KOLs", role: "Infectious disease specialists and guideline committee members.", weight: 0.22, pos: 1.15, neg: 0.88, orient: 1 },
          { slot: 2, display: "Community Internists / PCPs", canonical: "Community Physicians", role: "Community physicians managing infectious conditions in outpatient settings.", weight: 0.2, pos: 0.92, neg: 1.1, orient: 1 },
          { slot: 3, display: "Hospital Pharmacists / P&T", canonical: "Health Systems", role: "Formulary decision-makers, P&T committee members, and stewardship program leads.", weight: 0.18, pos: 0.9, neg: 1.08, orient: 1 },
          { slot: 4, display: "Payers / CMS / Access", canonical: "Payers / Access", role: "Coverage bodies with evolving reimbursement positions on novel agents.", weight: 0.16, pos: 0.82, neg: 1.18, orient: 1 },
          { slot: 5, display: "Professional Society Bodies", canonical: "Guideline Bodies", role: "Professional society guideline panels with high HCP deference (e.g., IDSA and equivalent bodies).", weight: 0.16, pos: 1.28, neg: 0.88, orient: 1 },
          { slot: 6, display: "Generic / Alternative Therapy Pressure", canonical: "Competitor Counteraction", role: "Generic equivalents or standard-of-care alternatives constraining adoption.", weight: 0.08, pos: 0.9, neg: 1.1, orient: -1 },
        ],
      },
    ];

    for (const sp of specialtyProfiles) {
      for (const actor of sp.actors) {
        await db.insert(specialtyActorSetsTable).values({
          id: randomUUID(),
          primarySpecialtyProfile: sp.profile,
          actorSlot: actor.slot,
          displayActor: actor.display,
          canonicalActor: actor.canonical,
          roleInSystem: actor.role,
          baseInfluenceWeight: actor.weight,
          basePositiveResponseFactor: actor.pos,
          baseNegativeResponseFactor: actor.neg,
          outcomeOrientation: actor.orient,
        });
      }
    }

    await db.insert(caseLibraryTable).values([
      {
        id: randomUUID(),
        caseId: "ANALOG-001",
        therapyArea: "Rare / orphan disease",
        productType: "Medication",
        specialty: "Specialist-led / academic center",
        evidenceType: "Phase 3 RCT",
        lifecycleStage: "Launch / early adoption",
        actorMix: "KOL-led with community resistance",
        marketAccessConditions: "Specialty pharmacy, prior auth required",
        outcomePattern: "Delayed adoption — 18-24 months to meaningful uptake",
        adoptionTrajectory: "Slow ramp, then inflection after guideline inclusion",
        keyInflectionSignals: "Society guideline mention, payer policy expansion",
        finalObservedOutcome: "Moderate adoption in academic centers; limited community penetration",
        finalProbability: 0.55,
        notes: "Strong KOL support did not translate to community at launch. Guideline endorsement was the key inflection.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-002",
        therapyArea: "Cardiovascular",
        productType: "Device",
        specialty: "Cardiology / Interventional",
        evidenceType: "Real-world evidence + RCT",
        lifecycleStage: "Growth phase",
        actorMix: "Interventionalist-led, hospital system adoption",
        marketAccessConditions: "DRG + add-on payment, coverage expanding",
        outcomePattern: "Rapid uptake among early adopters, broader market needed",
        adoptionTrajectory: "Fast in high-volume centers, slower in community",
        keyInflectionSignals: "Society guideline class IIa, national coverage decision",
        finalObservedOutcome: "Strong adoption at academic centers; community lag remains",
        finalProbability: 0.72,
        notes: "Operator dependence and center volume requirements created uneven rollout across site types.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-003",
        therapyArea: "Infectious disease",
        productType: "Medication",
        specialty: "Infectious Disease / Specialist",
        evidenceType: "Retrospective registry + open-label extension",
        lifecycleStage: "Established use",
        actorMix: "Specialist and generalist co-managing",
        marketAccessConditions: "Favorable access after initial coverage challenge",
        outcomePattern: "Gradual guideline-anchored adoption",
        adoptionTrajectory: "Consistent upward trend after joint guideline update",
        keyInflectionSignals: "Joint society guideline, payer coverage liberalization",
        finalObservedOutcome: "Near-guideline-level adoption in academic specialist centers",
        finalProbability: 0.68,
        notes: "Classic guideline-anchored adoption — payer resistance resolved after evidence base matured.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-004",
        therapyArea: "Respiratory / chronic disease",
        productType: "Medication",
        specialty: "Pulmonology / community",
        evidenceType: "Phase 3 RCT (exacerbation endpoint)",
        lifecycleStage: "Mature — label expansion phase",
        actorMix: "Community specialists, payer-sensitive",
        marketAccessConditions: "Commercially competitive, step therapy required",
        outcomePattern: "Plateau after initial launch, rebooted by label expansion",
        adoptionTrajectory: "Flat then upward after indication expansion",
        keyInflectionSignals: "Exacerbation data publication, label expansion approval",
        finalObservedOutcome: "Broad community adoption after data universally accepted",
        finalProbability: 0.63,
        notes: "Step therapy hurdles delayed adoption. Definitive exacerbation data was the trigger for payer capitulation.",
      },
      {
        id: randomUUID(),
        caseId: "ANALOG-005",
        therapyArea: "Oncology",
        productType: "Medication",
        specialty: "Oncology / community + academic",
        evidenceType: "Phase 3 RCT (OS endpoint)",
        lifecycleStage: "Launch",
        actorMix: "Academic-led, pathway committee dependent",
        marketAccessConditions: "Pathway-controlled, payer prior auth required",
        outcomePattern: "Academic adoption fast, community gated by pathway inclusion",
        adoptionTrajectory: "Two-wave: academic early, community after pathway update",
        keyInflectionSignals: "OS data publication, NCCN pathway Category 1 inclusion",
        finalObservedOutcome: "Strong overall adoption after pathway committee endorsement",
        finalProbability: 0.74,
        notes: "Tumor board and pathway committee dynamics were the decisive behavioral gating mechanism.",
      },
    ]);

    await db.insert(calibrationLogTable).values({
      id: randomUUID(),
      forecastId: "FCAST-DEMO",
      caseId: "CASE-DEMO-01",
      predictedProbability: 0.45,
      notes: "Baseline prior only — no signals computed yet.",
      snapshotJson: JSON.stringify({ version: "baseline", priorProbability: 0.45 }),
    });

    await db.insert(scenariosTable).values([
      {
        id: randomUUID(),
        scenarioId: "SCN-001",
        caseId: "CASE-DEMO-01",
        hypotheticalSignal: "Single additional high-strength positive signal",
        direction: "Positive",
        estimatedImpact: 0.15,
        newProbability: 0.60,
        notes: "Illustrative upside sensitivity — e.g. society guideline endorsement",
      },
      {
        id: randomUUID(),
        scenarioId: "SCN-002",
        caseId: "CASE-DEMO-01",
        hypotheticalSignal: "Single additional high-strength negative signal",
        direction: "Negative",
        estimatedImpact: -0.12,
        newProbability: 0.33,
        notes: "Illustrative downside sensitivity — e.g. safety signal or payer restriction",
      },
    ]);

    await db.insert(guidanceTable).values([
      {
        id: randomUUID(),
        guidanceId: "GUID-001",
        caseId: "CASE-DEMO-01",
        keyRiskDriver: "Academic KOLs",
        recommendedAction: "Leverage supportive KOL sentiment to accelerate peer-to-peer adoption momentum.",
        targetAudience: "Medical Affairs / Field",
        priorityLevel: "High",
        linkedSignalId: "CS-001",
      },
      {
        id: randomUUID(),
        guidanceId: "GUID-002",
        caseId: "CASE-DEMO-01",
        keyRiskDriver: "Identification / referral gap (Field intelligence)",
        recommendedAction: "Route simplification barrier to MIOS and OHOS for coordinated field response.",
        targetAudience: "Field strategy / Sales",
        priorityLevel: "High",
        linkedSignalId: "CS-002",
      },
      {
        id: randomUUID(),
        guidanceId: "GUID-003",
        caseId: "CASE-DEMO-01",
        keyRiskDriver: "Access / reimbursement environment",
        recommendedAction: "Monitor payer coverage expansion; accelerate pull-through when confirmed.",
        targetAudience: "Market Access",
        priorityLevel: "Medium",
        linkedSignalId: "CS-003",
      },
    ]);

    await db.insert(fieldIntelligenceTable).values({
      id: randomUUID(),
      feedbackId: "FB-001",
      brand: "ARIKAYCE",
      audienceType: "HCP",
      specialty: "Specialist",
      subspecialty: "Academic center",
      region: "US",
      sourceRole: "MSL",
      sourceName: "Field representative",
      signalCategory: "Clinical perception",
      observedBarrier: "Physicians are asking for a clearer connection between clinical trial endpoints and real-world patient outcomes.",
      rawFieldFeedback:
        "KOLs at target accounts want a simpler narrative linking the primary endpoint to day-to-day patient experience — the data story is not landing without that bridge.",
      beliefShiftRisk: 4,
      messageMismatchRisk: 5,
      accessRisk: 1,
      competitiveRisk: 1,
      urgencyScore: 5,
      credibilityScore: 4,
      frequencyScore: 3,
      potentialImpact: 5,
      totalSignalScore: 17,
      ciosSignalDirection: "Negative",
      suggestedRoute: "CIOS→MIOS+OHOS",
      fieldActionNeeded: "Yes",
      notes: "Recommend message bridge: endpoint to patient-relevant outcome framing.",
    });

    await db.insert(watchlistTable).values([
      {
        id: randomUUID(),
        signalId: "SIG-W-001",
        signalName: "Society guideline update",
        signalType: "Regulatory / clinical",
        expectedWindow: "Next major society congress",
        owner: "Medical Affairs",
        expectedDirection: "+",
        estimatedImpact: "High",
        evidenceSource: "Society meeting calendar",
        status: "Pending",
        notes: "Guideline panel discussion expected; monitor abstract submissions.",
      },
      {
        id: randomUUID(),
        signalId: "SIG-W-002",
        signalName: "Payer coverage expansion",
        signalType: "Commercial / access",
        expectedWindow: "Next 6 months",
        owner: "Market Access",
        expectedDirection: "+",
        estimatedImpact: "Medium",
        evidenceSource: "Payer policy monitoring",
        status: "Pending",
        notes: "Tracking policy bulletins across top payer accounts.",
      },
      {
        id: randomUUID(),
        signalId: "SIG-W-003",
        signalName: "Confirmatory trial data readout",
        signalType: "Clinical evidence",
        expectedWindow: "Q4 current year",
        owner: "Clinical / Medical",
        expectedDirection: "+",
        estimatedImpact: "High",
        evidenceSource: "Clinical trial registry",
        status: "Pending",
        notes: "Interim analysis expected; watch for press release and data congress presentation.",
      },
      {
        id: randomUUID(),
        signalId: "SIG-W-004",
        signalName: "Competitor label expansion",
        signalType: "Competitive",
        expectedWindow: "6–12 months",
        owner: "Competitive Intelligence",
        expectedDirection: "-",
        estimatedImpact: "Medium",
        evidenceSource: "FDA pipeline tracker / competitor IR",
        status: "Pending",
        notes: "Monitor competitor regulatory filings and approval timeline.",
      },
    ]);

    return { success: true, message: "Database seeded with generic CIOS demonstration data." };
  } catch (error) {
    return { success: false, message: `Seed failed: ${error}` };
  }
}
