import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import casesRouter from "./cases.js";
import signalsRouter from "./signals.js";
import actorsRouter from "./actors.js";
import forecastsRouter from "./forecasts.js";
import analogsRouter from "./analogs.js";
import calibrationRouter from "./calibration.js";
import learningRouter from "./learning.js";
import scenariosRouter from "./scenarios.js";
import guidanceRouter from "./guidance.js";
import fieldRouter from "./field.js";
import watchlistRouter from "./watchlist.js";
import seedRouter from "./seed.js";
import discoverRouter from "./discover.js";
import simulationRouter from "./simulation.js";
import intelligenceRouter from "./intelligence.js";
import portfolioRouter from "./portfolio.js";
import decisionPathRouter from "./decision-paths.js";
import scenarioAdapterRouter from "./scenario-adapter.js";
import forecastLedgerRouter from "./forecast-ledger.js";
import narrativeRouter from "./narrative.js";
import signalWatchlistRouter from "./signal-watchlist.js";
import weeklyBriefRouter from "./weekly-brief.js";
import competitorBehaviorsRouter from "./competitor-behaviors.js";
import targetEntitiesRouter from "./target-entities.js";
import adopterDiscoveryRouter from "./adopter-discovery.js";
import auditLogsRouter from "./audit-logs.js";
import signalDetectionRouter from "./signal-detection.js";
import recalculateRouter from "./recalculate.js";
import aiSignalsRouter from "./ai-signals.js";
import aiDecideRouter from "./ai-decide.js";
import aiInterpretRouter from "./ai-interpret.js";
import importProjectRouter from "./import-project.js";
import aiRespondRouter from "./ai-respond.js";
import aiSimulateRouter from "./ai-simulate.js";
import aiArchetypeRouter from "./ai-archetype.js";
import aiAssumptionsRouter from "./ai-assumptions.js";
import agentQuestionStructuringRouter from "./agent-question-structuring.js";
import agentExternalSignalScoutRouter from "./agent-external-signal-scout.js";
import agentSignalNormalizerRouter from "./agent-signal-normalizer.js";
import agentCaseComparatorRouter from "./agent-case-comparator.js";
import agentActorSegmentationRouter from "./agent-actor-segmentation.js";
import agentPrioritizationRouter from "./agent-prioritization.js";
import agentSignalQualityRouter from "./agent-signal-quality.js";
import agentConflictResolverRouter from "./agent-conflict-resolver.js";
import agentIntegrityRouter from "./agent-integrity.js";
import agentStakeholderReactionRouter from "./agent-stakeholder-reaction.js";
import agentMiosRouter from "./agent-mios.js";
import agentBaosRouter from "./agent-baos.js";
import signalDependencyRouter from "./signal-dependency.js";
import referenceCasesRouter from "./reference-cases.js";
import adoptionSegmentsRouter from "./adoption-segments.js";
import barrierDiagnosisRouter from "./barrier-diagnosis.js";
import caseFeedbackRouter from "./case-feedback.js";
import caseTypeRouter from "./case-type.js";
import readinessTimelineRouter from "./readiness-timeline.js";
import competitiveRiskRouter from "./competitive-risk.js";
import growthFeasibilityRouter from "./growth-feasibility.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(casesRouter);
router.use(signalsRouter);
router.use(actorsRouter);
router.use(forecastsRouter);
router.use(analogsRouter);
router.use(calibrationRouter);
router.use(learningRouter);
router.use(scenariosRouter);
router.use(guidanceRouter);
router.use(fieldRouter);
router.use(watchlistRouter);
router.use(seedRouter);
router.use(discoverRouter);
router.use(simulationRouter);
router.use(intelligenceRouter);
router.use(portfolioRouter);
router.use(decisionPathRouter);
router.use(scenarioAdapterRouter);
router.use(forecastLedgerRouter);
router.use(narrativeRouter);
router.use(signalWatchlistRouter);
router.use(weeklyBriefRouter);
router.use(competitorBehaviorsRouter);
router.use(targetEntitiesRouter);
router.use(adopterDiscoveryRouter);
router.use(auditLogsRouter);
router.use(signalDetectionRouter);
router.use(recalculateRouter);
router.use(aiSignalsRouter);
router.use(aiDecideRouter);
router.use(aiInterpretRouter);
router.use(importProjectRouter);
router.use(aiRespondRouter);
router.use(aiSimulateRouter);
router.use(aiArchetypeRouter);
router.use(aiAssumptionsRouter);
router.use(agentQuestionStructuringRouter);
router.use(agentExternalSignalScoutRouter);
router.use(agentSignalNormalizerRouter);
router.use(agentCaseComparatorRouter);
router.use(agentActorSegmentationRouter);
router.use(agentPrioritizationRouter);
router.use(agentSignalQualityRouter);
router.use(agentConflictResolverRouter);
router.use(agentIntegrityRouter);
router.use(agentStakeholderReactionRouter);
router.use(agentMiosRouter);
router.use(agentBaosRouter);
router.use(signalDependencyRouter);
router.use(referenceCasesRouter);
router.use(adoptionSegmentsRouter);
router.use(barrierDiagnosisRouter);
router.use(caseFeedbackRouter);
router.use(caseTypeRouter);
router.use(readinessTimelineRouter);
router.use(competitiveRiskRouter);
router.use(growthFeasibilityRouter);

export default router;
