import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import casesRouter from "./cases.js";
import signalsRouter from "./signals.js";
import actorsRouter from "./actors.js";
import forecastsRouter from "./forecasts.js";
import analogsRouter from "./analogs.js";
import calibrationRouter from "./calibration.js";
import learningRouter from "./learning.js";
import scenariosRouter from "./scenarios.js";
import guidanceRouter from "./guidance.js";
import fieldRouter from "./field.js";
import watchlistRouter from "./watchlist.js";
import seedRouter from "./seed.js";
import discoverRouter from "./discover.js";
import simulationRouter from "./simulation.js";
import intelligenceRouter from "./intelligence.js";
import portfolioRouter from "./portfolio.js";
import decisionPathRouter from "./decision-paths.js";
import scenarioAdapterRouter from "./scenario-adapter.js";
import forecastLedgerRouter from "./forecast-ledger.js";
import narrativeRouter from "./narrative.js";
import signalWatchlistRouter from "./signal-watchlist.js";
import weeklyBriefRouter from "./weekly-brief.js";
import competitorBehaviorsRouter from "./competitor-behaviors.js";
import targetEntitiesRouter from "./target-entities.js";
import adopterDiscoveryRouter from "./adopter-discovery.js";
import auditLogsRouter from "./audit-logs.js";
import signalDetectionRouter from "./signal-detection.js";
import recalculateRouter from "./recalculate.js";
import aiSignalsRouter from "./ai-signals.js";
import aiDecideRouter from "./ai-decide.js";
import aiInterpretRouter from "./ai-interpret.js";
import importProjectRouter from "./import-project.js";
import aiRespondRouter from "./ai-respond.js";
import aiSimulateRouter from "./ai-simulate.js";
import aiArchetypeRouter from "./ai-archetype.js";
import aiAssumptionsRouter from "./ai-assumptions.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(casesRouter);
router.use(signalsRouter);
router.use(actorsRouter);
router.use(forecastsRouter);
router.use(analogsRouter);
router.use(calibrationRouter);
router.use(learningRouter);
router.use(scenariosRouter);
router.use(guidanceRouter);
router.use(fieldRouter);
router.use(watchlistRouter);
router.use(seedRouter);
router.use(discoverRouter);
router.use(simulationRouter);
router.use(intelligenceRouter);
router.use(portfolioRouter);
router.use(decisionPathRouter);
router.use(scenarioAdapterRouter);
router.use(forecastLedgerRouter);
router.use(narrativeRouter);
router.use(signalWatchlistRouter);
router.use(weeklyBriefRouter);
router.use(competitorBehaviorsRouter);
router.use(targetEntitiesRouter);
router.use(adopterDiscoveryRouter);
router.use(auditLogsRouter);
router.use(signalDetectionRouter);
router.use(recalculateRouter);
router.use(aiSignalsRouter);
router.use(aiDecideRouter);
router.use(aiInterpretRouter);
router.use(importProjectRouter);
router.use(aiRespondRouter);
router.use(aiSimulateRouter);
router.use(aiArchetypeRouter);
router.use(aiAssumptionsRouter);

export default router;
